name: wheat3dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - pip=22.3.1
  - numpy
  - scipy
  - matplotlib
  - pillow
  - jupyterlab
  - ipykernel
  - ipython
  - scikit-learn
  - shapely
  - ffmpeg
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pyqt
  - plyfile
  - tqdm
  - pyyaml
  - pip:
      - wandb
      - ffmpeg-python
      - gitpython
      - opencv-python
      - joblib
      - submodules/simple-knn
      - submodules/diff-gaussian-rasterization
      - submodules/flashsplat-rasterization